# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-20 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likenum', models.BigIntegerField(blank=True, null=True)),
                ('commentnum', models.BigIntegerField(blank=True, null=True)),
                ('repeatnum', models.BigIntegerField(blank=True, null=True)),
                ('datetime', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sina1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_name', models.CharField(blank=True, max_length=64, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('likenum', models.BigIntegerField(blank=True, null=True)),
                ('datetime', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'sina1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sina2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeatname', models.CharField(blank=True, max_length=125, null=True)),
                ('repeatnum', models.BigIntegerField(blank=True, null=True)),
                ('datetime', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'sina2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sina3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=125, null=True)),
                ('gender', models.CharField(blank=True, max_length=30, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('follow', models.BigIntegerField(blank=True, null=True)),
                ('fans', models.BigIntegerField(blank=True, null=True)),
                ('webnum', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sina3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sina4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fansparent', models.CharField(blank=True, max_length=255, null=True)),
                ('fansname', models.CharField(blank=True, max_length=255, null=True)),
                ('fanslevel', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sina4',
                'managed': False,
            },
        ),
    ]
